update_gitlab_repo:
  script:
    - git clone https://github.com/your-username/your-github-repo.git
    - cd your-github-repo
    - git remote add gitlab https://gitlab.com/your-username/your-gitlab-repo.git
    - git push gitlab HEAD:master
  only:
    - triggers
