update_gitlab_repo:
  script:
    - git clone https://github.com/OnlyShoky/Detectron2-STAC-SODA10m.git
    - cd Detectron2-STAC-SODA10m
    - git remote add gitlab https://gitlab.extend.internal.expleogroup.com/mohamed.el-mourabit-agharbi/Detectron2-STAC-SODA10m.git
    - git push gitlab HEAD:master
  only:
    - triggers
